;; (message "script: %s" "rconf.el")

;;; Add the "rc/*" directory to the load path
(push "~/.dotmacs.d/rc" load-path)

;;; Core Packages
(require 'init-evil)
(require 'init-doom-themes)
(require 'init-doom-modeline)
(provide 'init-tree-sitter)
(require 'init-winum)
(require 'init-all-the-icons)
(require 'init-page-break-lines)
(require 'init-paren-face)
(require 'init-line-number)
(require 'init-which-key)
(require 'init-general)
(require 'init-yascroll)
(require 'init-reverse-im)
(require 'init-dashboard)
(require 'init-dired)
(require 'init-zoom)
(require 'init-zoom-window)
(require 'init-vterm)
(require 'init-helm)
(require 'init-popup)
(require 'init-windmove)
(require 'init-base) ;; todo; clean and muve to basic section
;; (require 'init-font-lock) ; switch to tree-sitter
;; (require 'init-ivy) ; switch to helm

;;; Core Extendend Packages
(require 'init-fuzzy)
(require 'init-restart-emacs)
(require 'init-xclip)
(require 'init-ace-jump-mode)
(require 'init-ace-window)
(require 'init-vi-tilde-fringe)
(require 'init-whitespace)
(require 'init-paren)
(require 'init-symbol-overlay)
(require 'init-auto-sudoedit)
(require 'init-autorevert)
(require 'init-multiple-cursors)
(require 'init-saveplace)
(require 'init-ansi-color)
(require 'init-elec-pair)
(require 'init-hl-line)
(require 'init-highlight-numbers)
(require 'init-hl-todo)
(require 'init-volatile-highlights)
(require 'init-pretty-mode)
(require 'init-prog-mode)
(require 'init-cc-mode)
(require 'init-default-text-scale)
(require 'init-focus-autosave-mode)
(require 'init-dumb-jump)
(require 'init-dash)
(require 'init-launch)
(require 'init-locate)
(require 'init-memory-usage)
(require 'init-bug-hunter)
(require 'init-time)
(require 'init-editorconfig)
(require 'init-git-timemachine)
(require 'init-markdown)
(require 'init-nginx-mode)
(require 'init-cmake-mode)
(require 'init-gnuplot-mode)

;;; Autocomplete Packages
;; (require 'init-irony)
(require 'init-company)
;; (require 'init-cmake-ide)
;; (require 'init-rtags)
;; (require 'init-lsp-mode)
;; (require 'init-eglot)
;; (require 'init-auto-complete)
;; (require 'init-ctags)
(require 'init-ggtags)
;; (require 'init-ycmd)
;; (require 'init-flycheck)

;;; Useful Packages
(require 'init-diminish)
(require 'init-speed-type)
(require 'init-rainbow-mode)
(require 'init-flyspell)
(require 'init-profiler)
(require 'init-yasnippet)
(require 'init-expand-region)
(require 'init-google-translate)
(require 'init-google-this)
(require 'init-tramp)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; (require 'init-shell)
;; (require 'init-popup)
;; (require 'init-smooth-scrolling)
;; (require 'init-counsel)
;; (require 'auto-complete-c-headers)
;; Unconfigured Packages
;; (require 'init-column-marker)
;; (require 'init-dimmer)
;; (require 'init-project)
;; (require 'init-awesome-tab)
;; (require 'init-simple)
;; (require 'init-winner)
;; (require 'init-projectile)
;; (require 'init-fill-column-indicator)
;; (require 'init-typit)
;; (require 'init-vimish-fold)
(require 'init-hideshow)
(require 'init-avy)
(require 'init-uniquify)

;; Tested Packages
;; (require 'init-highlight-indent-guides)
;; (require 'init-avy)
;; (require 'init-recentf)
;; (require 'init-auto-compile)
;; (require 'init-auto-complete)
;; (require 'init-frame)
;; (require 'init-ibuffer)

;; (require 'init-smooth-scroll)
(require 'init-undo-tree)


(provide 'rconf)
