;;; Add the "rc/*" directory to the load path
(push "~/.dotmacs.d/rc" load-path)

;; Basic Packages
(require 'init-evil)
(require 'init-doom-themes)
(require 'init-doom-modeline)
(require 'init-font-lock)
(require 'init-xclip)
(require 'init-diminish)
(require 'init-dired)
(require 'init-ace-jump-mode)
(require 'init-golden-ratio)
(require 'init-paren-face)
(require 'init-zoom-window)
(require 'init-auto-complete)
(require 'init-which-key)
(require 'init-general)
;; (require 'init-yascroll)
;; (require 'init-reverse-im)

;; Extendend Packages
(require 'init-base) ;; todo; clean and muve to basic section
(require 'init-vi-tilde-fringe)
(require 'init-whitespace)
(require 'init-undo-tree)
(require 'init-markdown)
(require 'init-multiple-cursors)
(require 'init-saveplace)
(require 'init-paren)
(require 'init-elec-pair)
(require 'init-symbol-overlay)
(require 'init-ansi-color)
(require 'init-all-the-icons)
(require 'init-restart-emacs)
(require 'init-hl-line)
(require 'init-page-break-lines)
(require 'init-highlight-numbers)
(require 'init-default-text-scale)
(require 'init-focus-autosave-mode)
(require 'init-sudo-edit)
(require 'init-hl-todo)
(require 'init-shell)
(require 'init-counsel)
(require 'init-prog-mode)
(require 'init-vimish-fold)
(require 'init-nginx-mode)
(require 'init-cmake-mode)
(require 'init-cmake-ide)
(require 'init-dumb-jump)
(require 'init-dash)
(require 'init-autorevert)
(require 'init-launch)
(require 'init-locate)
(require 'init-memory-usage)
(require 'init-window-number)
(require 'init-volatile-highlights)
(require 'init-gnuplot-mode)
(require 'init-web-search)
(require 'init-pretty-mode)
(require 'init-bug-hunter)
(require 'init-line-number)
(require 'init-time)
(require 'init-editorconfig)
(require 'init-git-timemachine)
(require 'init-popup)
;; (require 'auto-complete-c-headers)

;; Unconfigured Packages
;; (require 'init-column-marker)
;; (require 'init-dimmer)
;; (require 'init-project)
;; (require 'init-awesome-tab)
;; (require 'init-rainbow-mode)
;; (require 'init-simple)
;; (require 'init-winner)
;; (require 'init-projectile)
;; (require 'init-fill-column-indicator)
;; (require 'init-typit)

;; Tested Packages
;; (require 'init-highlight-indent-guides)
;; (require 'init-avy)
;; (require 'init-recentf)
;; (require 'init-auto-compile)
;; (require 'init-server)
;; (require 'init-frame)
;; (require 'init-ibuffer)

(provide 'rconf)
